
### GET VID INFO
POST http://localhost:3000/api/v1/video/info HTTP/1.1
content-type: application/json

{
  "url": "https://www.youtube.com/watch?v=YCZu78lVESY"
}


### GET VID FULL META DATA
GET http://localhost:3000/api/v1/video/info/meta-data?url=https://www.youtube.com/watch?v=YCZu78lVESY HTTP/1.1
content-type: application/json


### DOWNLOAD VIDEO
POST http://localhost:3000/api/v1/video/download HTTP/1.1
content-type: application/json

{
  "url": "https://www.youtube.com/watch?v=YCZu78lVESY",
  "quality": "480",
  "audioOnly": false
}

### SERVE VIDEO
GET http://localhost:3000/api/v1/video/download/The%204%20Stages%20Of%20Being%20A%20Software%20Dev.mp4 HTTP/1.1
content-type: application/json

### FORMATS AND QUALITY
POST http://localhost:3000/api/v1/video/info/quality-formats HTTP/1.1
content-type: application/json

{
  "url": "https://youtu.be/pBa_QBlW4OA?si=yKrgc5QAyrdqYrfC"
}
